image:
#  - Visual Studio 2022
#  - Visual Studio 2019
#  - Visual Studio 2017
  - Visual Studio 2015
#  - Visual Studio 2013

install:
  - appveyor-retry cinst winflexbison
  - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
  - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
# https://www.appveyor.com/docs/lang/cpp/
#  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
#  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64


configuration:
  - Release

before_build:
  - perl src/tools/msvc/mkvcbuild.pl

build:
  project: pgsql.sln

test_script:
  - cd src/tools/msvc && vcregress check
  - cd src/tools/msvc && vcregress ecpgcheck
